# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: News
    url: 'news/news'
    weight: 20
  - name: Publications
    url: '/publication'
    weight: 30
  - name: Teachings
    url: '/teaching/teachings'
    weight: 40
  - name: Services
    url: '/service/services'
    weight: 50
  - name: Talks
    url: '/talk/talks'
    weight: 60
  - name: Awards
    url: '/award/awards'
    weight: 70
  # - name: Contact
  #   url: '#contact'
  #   weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/cv.pdf
#    weight: 70
